version: '3'

services:
  mariadb:
    image: 'bitnami/mariadb:latest'
    environment:
      - MARIADB_ROOT_PASSWORD=moodle
      - MARIADB_USER=moodle
      - MARIADB_PASSWORD=moodle
      - MARIADB_DATABASE=moodle
    volumes:
      - /Users/jon/documents/docker/mariadb-persistence:/bitnami/mariadb
    ports:
      - '3306:3306'

  moodle:
    image: 'bitnami/moodle:latest'
    ports:
      - '8080:8080'
      - '8443:8443'
    environment:
      - MOODLE_DATABASE_HOST=mariadb
      - MOODLE_DATABASE_USER=moodle
      - MOODLE_DATABASE_PASSWORD=moodle
      - MOODLE_DATABASE_NAME=moodle
    volumes:
      - /Users/jon/documents/docker/moodle-persistence:/bitnami/moodle
    depends_on:
      - mariadb
